### ISSUE TITLE
Chlamydomonas reference data download and prep

### ISSUE THREAD

**Issue by splaisan** [BrendelGroup/AEGeAn#263]
Hi,

**running: AEGeAn vv0.15.1+216.g4b00f0a from the singularity img**

New to the pipeline, the test command with -h worked so I can execute the image
I then tried to get the reference genome with the singularity image and it failed:

I deduced the prefix for Chlamydomonas reinhardtii as being **Crei** which seems OK and recycled the commands from https://github.com/standage/genhub/blob/master/docs/MANUAL.md

```
pfx_cmd="singularity exec -e -B $(pwd) ${NXF_SINGULARITY_CACHEDIR}/aegean.sif "

${pfx_cmd} fidibus --workdir=${workdir} --refr=Crei download
[fidibus: Chlamydomonas reinhardtii] download genome sequence from RefSeq
[fidibus: Chlamydomonas reinhardtii] download genome annotation from RefSeq
[fidibus: Chlamydomonas reinhardtii] download protein sequences from RefSeq
[fidibus: Chlamydomonas reinhardtii] build complete!
[fidibus] all builds complete!
```

then I tried to prep after download and it failed

```
${pfx_cmd} fidibus --workdir=${workdir} --refr=Crei prep
[Genome: Chlamydomonas reinhardtii] preprocess genome sequence file
[Genome: Chlamydomonas reinhardtii] preprocess annotation file
warning: attribute "product=" on line 105112 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105113 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105114 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105115 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105116 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105117 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105118 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105119 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105120 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105121 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105122 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105123 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105124 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105125 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182204 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182205 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182206 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182207 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182208 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182209 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182210 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182385 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182386 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182387 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182388 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182389 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182390 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194118 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194119 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194120 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194121 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194122 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194123 in file "stdin" has no value; skip it
[Genome: Chlamydomonas reinhardtii] preprocess protein sequence file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus", line 41, in run_build
    db.prep(strict=not args.relax)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/LocusPocus/genomedb.py", line 227, in prep
    self.preprocess_prot(logstream=logstream, verify=verify, strict=strict)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/LocusPocus/genomedb.py", line 307, in preprocess_prot
    self.preprocess('prot', logstream, verify, strict)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/LocusPocus/genomedb.py", line 289, in preprocess
    raise Exception(message)
Exception: Crei protein sequence file integrity check failed
6a8a16e0c1a583f5ee54126625b20c7fae436380
b5dc2092f56b9f675be8a2418b1588c3fd6b6dc8

To proceed in spite of this failure, re-run with the `--relax` option enabled.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/fidibus", line 4, in <module>
    __import__('pkg_resources').run_script('LocusPocus==0.15.1+216.g4b00f0a', 'fidibus')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus", line 240, in <module>
    main(get_parser().parse_args())
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus", line 222, in main
    _ = [p.get() for p in results]
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus", line 222, in <listcomp>
    _ = [p.get() for p in results]
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
Exception: Crei protein sequence file integrity check failed
6a8a16e0c1a583f5ee54126625b20c7fae436380
b5dc2092f56b9f675be8a2418b1588c3fd6b6dc8

To proceed in spite of this failure, re-run with the `--relax` option enabled.
```

I tried --relax to see what happens

```
${pfx_cmd} fidibus --workdir=${workdir} --refr=Crei prep --relax
[Genome: Chlamydomonas reinhardtii] preprocess genome sequence file
[Genome: Chlamydomonas reinhardtii] preprocess annotation file
warning: attribute "product=" on line 105112 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105113 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105114 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105115 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105116 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105117 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105118 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105119 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105120 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105121 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105122 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105123 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105124 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105125 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182204 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182205 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182206 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182207 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182208 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182209 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182210 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182385 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182386 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182387 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182388 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182389 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182390 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194118 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194119 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194120 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194121 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194122 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194123 in file "stdin" has no value; skip it
[Genome: Chlamydomonas reinhardtii] preprocess protein sequence file
Warning: Crei protein sequence file integrity check failed
6a8a16e0c1a583f5ee54126625b20c7fae436380
b5dc2092f56b9f675be8a2418b1588c3fd6b6dc8, proceeding anyway
[fidibus: Chlamydomonas reinhardtii] build complete!
[fidibus] all builds complete!
```

Can I work with this or is it bad?
thanks for your help

**Comment by vpbrendel** [comment]
What you observe is a (useful) feature, not a problem. When you specify Crei on the command line, you look up the config file Crei.yml in the LocusPocus/genome_configs directory. The config file specifies what should be downloaded for Crei. For each of the files, there is a record of the shasum hash for the file at the time of definition of the Crei.yml configuration file (on Linux, the command 'shasum <file>' will generate this number). When you download at a later time point, although you have specified the same URLs, the files may have changed. That will result in a different checksum. Typically, this simply reflects an update by the genome providers. The error message you reported says that the protein file has changed since we created the Crei.yml file. This is good to know if you want to reproduce a result you derived some time ago. The message alerts you to the fact that your input has changed in the meantime.

If you want to work with the latest input file, then the --relax option accepts that input and proceeds. Which should be perfectly fine. If you are satisfied that this is the input you want, you can replace the previous checksum with the current value in the .yml file; i.e. in your case 6a8a16e0c1a583f5ee54126625b20c7fae436380 would replace b5dc2092f56b9f675be8a2418b1588c3fd6b6dc8.

Volker

**Comment by splaisan** [comment]
I would agree if this did not happen few minutes after i downloaded the dataset. I do not bilieve it just changed in that short amount if time.
Or I should go play loto rapidely.
Lol

**Comment by vpbrendel** [comment]
You are using our supplied Crei.yml files - which were created years ago. Thus the checksum difference is between the protein file from years ago and what the providers have now.

**Comment by splaisan** [comment]
Ok now i follow you.
Thanks for the clarification
