### ISSUE TITLE
Prepping a local genome from braker3 gff3 data

### ISSUE THREAD

**Issue by splaisan** [BrendelGroup/AEGeAn#264]
I assembled denovo a Chlamydomonas genome using SRA data and annotated it using braker3
I now want to compare my denovo annotations to the reference genome

When I feed fidibus with the braker gff3 it complains about format and does not succeed to build it properly

```
${pfx_cmd} fidibus -w=./ --local --label=Gnm1 --gdna=ont_draft_assembly_softmask.fasta --gff3=braker.gff3 --prot=braker.aa --refr=${refr} download prep iloci breakdown stats

[Genome: Gnm1] checking input files
[Genome: Gnm1] preprocess genome sequence file
Cannot verify integrity of Gnm1 genome sequence file without a checksum
[Genome: Gnm1] preprocess annotation file
Traceback (most recent call last):
  File "/usr/local/bin/fidibus-format-gff3.py", line 4, in <module>
    __import__('pkg_resources').run_script('LocusPocus==0.15.1+216.g4b00f0a', 'fidibus-format-gff3.py')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus-format-gff3.py", line 262, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus-format-gff3.py", line 255, in main
    for line in formatter:
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus-format-gff3.py", line 38, in __iter__
    line = self.parse_gene(line)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus-format-gff3.py", line 112, in parse_gene
    assert accmatch, 'unable to parse gene accession: %s' % line
AssertionError: unable to parse gene accession: contig_10       AUGUSTUS        gene    179571  180460  .       -       .       ID=g1;
Traceback (most recent call last):
  File "/usr/local/bin/seq-reg.py", line 60, in <module>
    print(entry)
BrokenPipeError: [Errno 32] Broken pipe
Cannot verify integrity of Gnm1 annotation file without a checksum
[Genome: Gnm1] preprocess protein sequence file
Cannot verify integrity of Gnm1 protein sequence file without a checksum
[Genome: Gnm1] computing interval loci
[Genome: Gnm1] merging iLoci
[Genome: Gnm1] determining simple iLoci
[Genome: Gnm1] selecting iLocus representatives
[Genome: Gnm1] extracting iLocus sequences
[Genome: Gnm1] iLoci ancillary data
[Genome: Gnm1] retrieving protein IDs
[Genome: Gnm1] extracting protein sequences
[Genome: Gnm1] parsing protein->iLocus alls mapping
[Genome: Gnm1] parsing protein->iLocus reps mapping
[Genome: Gnm1] calculating mature mRNA intervals
warning: GFF3 file ".//Gnm1/Gnm1.mrnas.temp" is empty
warning: GFF3 file ".//Gnm1/Gnm1.mrnas.temp" is empty
warning: GFF3 file ".//Gnm1/Gnm1.mrnas.temp" is empty
warning: GFF3 file ".//Gnm1/Gnm1.ilocus.mrnas.temp" is empty
warning: GFF3 file ".//Gnm1/Gnm1.ilocus.mrnas.temp" is empty
warning: GFF3 file ".//Gnm1/Gnm1.ilocus.mrnas.temp" is empty
[Genome: Gnm1] extracting pre-mRNA and mature mRNA sequences
warning: GFF3 file ".//Gnm1/Gnm1.all.mrnas.gff3" is empty
warning: GFF3 file ".//Gnm1/Gnm1.all.mrnas.gff3" is empty
warning: GFF3 file ".//Gnm1/Gnm1.all.mrnas.gff3" is empty
[Genome: Gnm1] extracting exon sequences
[Genome: Gnm1] extracting intron sequences
[Genome: Gnm1] extracting coding sequences
[Genome: Gnm1] calculating feature statistics
[fidibus: Gnm1] build complete!
[fidibus: Chlamydomonas reinhardtii] download genome sequence from RefSeq
[fidibus: Chlamydomonas reinhardtii] download genome annotation from RefSeq
[fidibus: Chlamydomonas reinhardtii] download protein sequences from RefSeq
[Genome: Chlamydomonas reinhardtii] preprocess genome sequence file
[Genome: Chlamydomonas reinhardtii] preprocess annotation file
warning: attribute "product=" on line 105112 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105113 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105114 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105115 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105116 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105117 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105118 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105119 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105120 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105121 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105122 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105123 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105124 in file "stdin" has no value; skip it
warning: attribute "product=" on line 105125 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182204 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182205 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182206 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182207 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182208 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182209 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182210 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182385 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182386 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182387 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182388 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182389 in file "stdin" has no value; skip it
warning: attribute "product=" on line 182390 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194118 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194119 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194120 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194121 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194122 in file "stdin" has no value; skip it
warning: attribute "product=" on line 194123 in file "stdin" has no value; skip it
[Genome: Chlamydomonas reinhardtii] preprocess protein sequence file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus", line 41, in run_build
    db.prep(strict=not args.relax)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/LocusPocus/genomedb.py", line 227, in prep
    self.preprocess_prot(logstream=logstream, verify=verify, strict=strict)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/LocusPocus/genomedb.py", line 307, in preprocess_prot
    self.preprocess('prot', logstream, verify, strict)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/LocusPocus/genomedb.py", line 289, in preprocess
    raise Exception(message)
Exception: Crei protein sequence file integrity check failed
6a8a16e0c1a583f5ee54126625b20c7fae436380
b5dc2092f56b9f675be8a2418b1588c3fd6b6dc8

To proceed in spite of this failure, re-run with the `--relax` option enabled.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/fidibus", line 4, in <module>
    __import__('pkg_resources').run_script('LocusPocus==0.15.1+216.g4b00f0a', 'fidibus')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus", line 240, in <module>
    main(get_parser().parse_args())
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus", line 222, in main
    _ = [p.get() for p in results]
  File "/usr/local/lib/python3.9/site-packages/LocusPocus-0.15.1+216.g4b00f0a-py3.9.egg/EGG-INFO/scripts/fidibus", line 222, in <listcomp>
    _ = [p.get() for p in results]
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
Exception: Crei protein sequence file integrity check failed
6a8a16e0c1a583f5ee54126625b20c7fae436380
b5dc2092f56b9f675be8a2418b1588c3fd6b6dc8

To proceed in spite of this failure, re-run with the `--relax` option enabled.
```

leading to most files in the output folder being empty. 

```
drwxr-xr-x 2 u0002316 domain users 4.0K Jan 10 14:22 .
drwxr-xr-x 4 u0002316 domain users 4.0K Jan 10 14:13 ..
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.all.cds.fa
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.all.mrnas.fa
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.all.mrnas.gff3
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.all.pre-mrnas.fa
-rw-r--r-- 1 u0002316 domain users  12M Jan 10 14:22 Gnm1.all.prot.fa
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.cds.fa
-rw-r--r-- 1 u0002316 domain users   49 Jan 10 14:23 Gnm1.cds.tsv
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.exons.fa
-rw-r--r-- 1 u0002316 domain users   81 Jan 10 14:23 Gnm1.exons.tsv
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.filens.tsv
-rw-r--r-- 1 u0002316 domain users 110M Jan 10 14:22 Gnm1.gdna.fa
-rw-r--r-- 1 u0002316 domain users 2.3K Jan 10 14:22 Gnm1.gff3
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.ilens.tsv
-rw-r--r-- 1 u0002316 domain users 109M Jan 10 14:23 Gnm1.iloci.fa
-rw-r--r-- 1 u0002316 domain users  11K Jan 10 14:22 Gnm1.iloci.gff3
-rw-r--r-- 1 u0002316 domain users 5.9K Jan 10 14:23 Gnm1.iloci.tsv
-rw-r--r-- 1 u0002316 domain users 2.3K Jan 10 14:22 Gnm1.ilocus.mrnas.gff3
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.ilocus.mrnas.temp
-rw-r--r-- 1 u0002316 domain users   17 Jan 10 14:22 Gnm1.ilocus.mrnas.tsv
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.introns.fa
-rw-r--r-- 1 u0002316 domain users   67 Jan 10 14:23 Gnm1.introns.tsv
-rw-r--r-- 1 u0002316 domain users 109M Jan 10 14:23 Gnm1.miloci.fa
-rw-r--r-- 1 u0002316 domain users 6.1K Jan 10 14:22 Gnm1.miloci.gff3
-rw-r--r-- 1 u0002316 domain users 7.0K Jan 10 14:23 Gnm1.miloci.tsv
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.mrnas.fa
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.mrnas.gff3
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.mrnas.temp
-rw-r--r-- 1 u0002316 domain users   51 Jan 10 14:23 Gnm1.mrnas.tsv
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.mrnas.txt
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.pre-mrnas.fa
-rw-r--r-- 1 u0002316 domain users   91 Jan 10 14:23 Gnm1.pre-mrnas.tsv
-rw-r--r-- 1 u0002316 domain users   20 Jan 10 14:23 Gnm1.protein2ilocus.repr.tsv
-rw-r--r-- 1 u0002316 domain users   20 Jan 10 14:23 Gnm1.protein2ilocus.tsv
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.prot.fa
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:23 Gnm1.protids.txt
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:22 Gnm1.simple-iloci.txt
-rw-r--r-- 1 u0002316 domain users 2.3K Jan 10 14:23 Gnm1.with-introns.gff3
-rw-r--r-- 1 u0002316 domain users    0 Jan 10 14:22 ilens.temp
```

Adding --relax does not fix this and I get the parsing error for contig_10 the same

Here is the top of my gff3 file for the first 3 genes

```
contig_10       AUGUSTUS        gene    179571  180460  .       -       .       ID=g1;
contig_10       AUGUSTUS        mRNA    179571  180460  0.26    -       .       ID=g1.t1;Parent=g1;
contig_10       AUGUSTUS        stop_codon      179571  179573  .       -       0       ID=g1.t1.stop1;Parent=g1.t1;
contig_10       AUGUSTUS        CDS     179571  180012  1       -       1       ID=g1.t1.CDS1;Parent=g1.t1;
contig_10       AUGUSTUS        exon    179571  180012  .       -       .       ID=g1.t1.exon1;Parent=g1.t1;
contig_10       AUGUSTUS        intron  180013  180149  1       -       .       ID=g1.t1.intron1;Parent=g1.t1;
contig_10       AUGUSTUS        CDS     180150  180460  0.26    -       0       ID=g1.t1.CDS2;Parent=g1.t1;
contig_10       AUGUSTUS        exon    180150  180460  .       -       .       ID=g1.t1.exon2;Parent=g1.t1;
contig_10       AUGUSTUS        start_codon     180458  180460  .       -       0       ID=g1.t1.start1;Parent=g1.t1;
contig_10       AUGUSTUS        gene    183557  184724  .       -       .       ID=g2;
contig_10       AUGUSTUS        mRNA    183557  184724  0.18    -       .       ID=g2.t1;Parent=g2;
contig_10       AUGUSTUS        stop_codon      183557  183559  .       -       0       ID=g2.t1.stop1;Parent=g2.t1;
contig_10       AUGUSTUS        CDS     183557  184588  0.18    -       0       ID=g2.t1.CDS1;Parent=g2.t1;
contig_10       AUGUSTUS        exon    183557  184588  .       -       .       ID=g2.t1.exon1;Parent=g2.t1;
contig_10       AUGUSTUS        intron  184589  184688  1       -       .       ID=g2.t1.intron1;Parent=g2.t1;
contig_10       AUGUSTUS        CDS     184689  184724  1       -       0       ID=g2.t1.CDS2;Parent=g2.t1;
contig_10       AUGUSTUS        exon    184689  184724  .       -       .       ID=g2.t1.exon2;Parent=g2.t1;
contig_10       AUGUSTUS        start_codon     184722  184724  .       -       0       ID=g2.t1.start1;Parent=g2.t1;
contig_10       AUGUSTUS        gene    185626  189410  .       -       .       ID=g3;
contig_10       AUGUSTUS        mRNA    185626  189410  0.47    -       .       ID=g3.t1;Parent=g3;
contig_10       AUGUSTUS        stop_codon      185626  185628  .       -       0       ID=g3.t1.stop1;Parent=g3.t1;
contig_10       AUGUSTUS        CDS     185626  187041  1       -       0       ID=g3.t1.CDS1;Parent=g3.t1;
contig_10       AUGUSTUS        exon    185626  187041  .       -       .       ID=g3.t1.exon1;Parent=g3.t1;
contig_10       AUGUSTUS        intron  187042  187313  1       -       .       ID=g3.t1.intron1;Parent=g3.t1;
contig_10       AUGUSTUS        CDS     187314  187439  1       -       0       ID=g3.t1.CDS2;Parent=g3.t1;
contig_10       AUGUSTUS        exon    187314  187439  .       -       .       ID=g3.t1.exon2;Parent=g3.t1;
contig_10       AUGUSTUS        intron  187440  187529  1       -       .       ID=g3.t1.intron2;Parent=g3.t1;
contig_10       AUGUSTUS        CDS     187530  187647  1       -       1       ID=g3.t1.CDS3;Parent=g3.t1;
contig_10       AUGUSTUS        exon    187530  187647  .       -       .       ID=g3.t1.exon3;Parent=g3.t1;
contig_10       AUGUSTUS        intron  187648  187844  0.47    -       .       ID=g3.t1.intron3;Parent=g3.t1;
contig_10       AUGUSTUS        CDS     187845  188077  0.47    -       0       ID=g3.t1.CDS4;Parent=g3.t1;
contig_10       AUGUSTUS        exon    187845  188077  .       -       .       ID=g3.t1.exon4;Parent=g3.t1;
contig_10       AUGUSTUS        intron  188078  188317  1       -       .       ID=g3.t1.intron4;Parent=g3.t1;
contig_10       AUGUSTUS        CDS     188318  188386  1       -       0       ID=g3.t1.CDS5;Parent=g3.t1;
contig_10       AUGUSTUS        exon    188318  188386  .       -       .       ID=g3.t1.exon5;Parent=g3.t1;
contig_10       AUGUSTUS        intron  188387  188657  1       -       .       ID=g3.t1.intron5;Parent=g3.t1;
contig_10       AUGUSTUS        CDS     188658  188797  1       -       2       ID=g3.t1.CDS6;Parent=g3.t1;
contig_10       AUGUSTUS        exon    188658  188797  .       -       .       ID=g3.t1.exon6;Parent=g3.t1;
contig_10       AUGUSTUS        intron  188798  189020  1       -       .       ID=g3.t1.intron6;Parent=g3.t1;
contig_10       AUGUSTUS        CDS     189021  189078  1       -       0       ID=g3.t1.CDS7;Parent=g3.t1;
contig_10       AUGUSTUS        exon    189021  189078  .       -       .       ID=g3.t1.exon7;Parent=g3.t1;
contig_10       AUGUSTUS        intron  189079  189212  1       -       .       ID=g3.t1.intron7;Parent=g3.t1;
contig_10       AUGUSTUS        CDS     189213  189410  1       -       0       ID=g3.t1.CDS8;Parent=g3.t1;
contig_10       AUGUSTUS        exon    189213  189410  .       -       .       ID=g3.t1.exon8;Parent=g3.t1;
contig_10       AUGUSTUS        start_codon     189408  189410  .       -       0       ID=g3.t1.start1;Parent=g3.t1;
...
```

Can you please help me solve this format issue to get a functional gff3 input file and a correct downstream processing?

thanks in advance

**Comment by vpbrendel** [comment]
The BRAKER generated gff3 file misses Name or accession attributes; see https://github.com/standage/genhub/blob/master/docs/MANUAL.md.

The following is a fix that seems to work on your input:
1) Create a script 'xfix" with the content

#!/bin/bash
#
sed -e "s#ID=g\([[:digit:]]\+\);#ID=g\1;Name=AUG_\1;#; s#ID=g\([[:digit:]]\+\)\.t\([[:digit:]]\+\);#ID=g\1\.t\2;Name=AUG_\1;#" $1

2) chmod a+x xfix

3) ./xfix braker.gff3 > fixed_braker.gff3

4) Use the fixed_braker.gff3 file in your commands.

Should work, but needs testing please.
Volker
